# Generated by Django 5.0.6 on 2024-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="qualifications",
        ),
        migrations.AddField(
            model_name="teacher",
            name="teacher_salary",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="country",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="gender",
            field=models.CharField(max_length=20),
        ),
    ]
