# Generated by Django 5.0.6 on 2024-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "teacher",
            "0002_remove_teacher_qualifications_teacher_teacher_salary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
