# Generated by Django 5.0.6 on 2024-08-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_alter_course_teacher"),
        ("teacher", "0006_alter_teacher_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="courses",
        ),
        migrations.AddField(
            model_name="teacher",
            name="courses",
            field=models.ManyToManyField(related_name="teachers", to="course.course"),
        ),
    ]
