# Generated by Django 5.0.6 on 2024-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_model", "0004_rename_assigned_teachers_classroom_teachers_assigned"),
        ("teacher", "0007_remove_teacher_courses_teacher_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="assigned_classrooms",
            field=models.ManyToManyField(
                related_name="assigned_teachers", to="class_model.classroom"
            ),
        ),
    ]
