# Generated by Django 5.0.6 on 2024-08-20 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0008_alter_teacher_assigned_classrooms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="assigned_classrooms",
            new_name="classrooms",
        ),
    ]
