# Generated by Django 5.0.6 on 2024-08-20 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0009_rename_assigned_classrooms_teacher_classrooms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="classrooms",
            new_name="assigned_classrooms",
        ),
    ]
