# Generated by Django 5.0.6 on 2024-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "class_model",
            "0007_rename_teachers_assigned_classroom_assigned_teachers_and_more",
        ),
        ("teacher", "0010_rename_classrooms_teacher_assigned_classrooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="assigned_classrooms",
            field=models.ManyToManyField(
                related_name="teachers_assigned", to="class_model.classroom"
            ),
        ),
    ]
