# Generated by Django 5.0.6 on 2024-08-13 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
        ("teacher", "0003_alter_teacher_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taught_courses",
                to="teacher.teacher",
            ),
        ),
    ]
