# Generated by Django 5.0.6 on 2024-08-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_model", "0001_initial"),
        ("teacher", "0003_alter_teacher_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="teacher",
        ),
        migrations.AddField(
            model_name="classroom",
            name="teachers",
            field=models.ManyToManyField(
                related_name="classrooms", to="teacher.teacher"
            ),
        ),
    ]
