# Generated by Django 5.0.6 on 2024-08-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_model", "0002_remove_classroom_teacher_classroom_teachers"),
        ("teacher", "0003_alter_teacher_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="teachers",
        ),
        migrations.AddField(
            model_name="classroom",
            name="assigned_teachers",
            field=models.ManyToManyField(
                related_name="classrooms_assigned", to="teacher.teacher"
            ),
        ),
    ]
