# Generated by Django 5.0.6 on 2024-08-20 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("class_model", "0003_remove_classroom_teachers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="assigned_teachers",
            new_name="teachers_assigned",
        ),
    ]
