# Generated by Django 5.0.6 on 2024-08-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_model", "0004_rename_assigned_teachers_classroom_teachers_assigned"),
        ("teacher", "0009_rename_assigned_classrooms_teacher_classrooms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="teachers_assigned",
        ),
        migrations.AddField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taught_classrooms",
                to="teacher.teacher",
            ),
        ),
    ]
