# Generated by Django 5.0.6 on 2024-08-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_model", "0005_remove_classroom_teachers_assigned_classroom_teacher"),
        ("teacher", "0010_rename_classrooms_teacher_assigned_classrooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="teachers_assigned",
            field=models.ManyToManyField(
                related_name="classrooms_assigned", to="teacher.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_teachers",
                to="teacher.teacher",
            ),
        ),
    ]
