# Generated by Django 5.0.6 on 2024-08-20 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("class_model", "0006_classroom_teachers_assigned_alter_classroom_teacher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="teachers_assigned",
            new_name="assigned_teachers",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="teacher",
        ),
    ]
