# Generated by Django 5.0.6 on 2024-07-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classPeriod", "0001_initial"),
        ("class_model", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classperiod",
            name="classrooms",
            field=models.ManyToManyField(
                related_name="class_Periods", to="class_model.classroom"
            ),
        ),
        migrations.AlterField(
            model_name="classperiod",
            name="courses",
            field=models.ManyToManyField(
                related_name="class_Periods", to="course.course"
            ),
        ),
        migrations.CreateModel(
            name="ClassPeriodClassPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classPeriod.classperiod",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_model.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
    ]
